In [1]:
# CELL 1 — Install dependencies

!pip install -q -U transformers peft accelerate bitsandbytes datasets huggingface_hub trl
!pip install -q -U sentencepiece safetensors protobuf rdkit tqdm

import os
import gc
import json
import random
import getpass
from pathlib import Path
from typing import Any, Dict, Optional

import torch

print("Torch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA capability:", torch.cuda.get_device_capability(0))
else:
    raise RuntimeError("CUDA is False. Enable GPU runtime before training.")

Torch: 2.8.0+cu128
CUDA: True
GPU: NVIDIA L40S
CUDA capability: (8, 9)

In [2]:
# CELL 2 — Login and config

from huggingface_hub import login, whoami, HfApi, snapshot_download

try:
    from google.colab import userdata
    HF_TOKEN = userdata.get("HF_TOKEN")
except Exception:
    HF_TOKEN = None

if not HF_TOKEN:
    HF_TOKEN = getpass.getpass("Paste Hugging Face token with write access: ")

login(token=HF_TOKEN)
HF_USERNAME = whoami(token=HF_TOKEN)["name"]

print("Logged in as:", HF_USERNAME)


# Model / project

BASE_MODEL = "Qwen/Qwen2.5-1.5B-Instruct"
HF_MODEL_REPO_NAME = "ord-retro-qwen25-15b"

LORA_REPO_ID = f"{HF_USERNAME}/{HF_MODEL_REPO_NAME}-lora"
MERGED_REPO_ID = f"{HF_USERNAME}/{HF_MODEL_REPO_NAME}-merged-fp16"


# Paths

WORK_DIR = Path("/content/ord_retro_training")
DATA_DIR = WORK_DIR / "prepared_data"
OUTPUT_DIR = WORK_DIR / "trainer_output"
ADAPTER_DIR = WORK_DIR / "lora_adapter"
MERGED_DIR = WORK_DIR / "merged_fp16"

TRAIN_JSONL = DATA_DIR / "train_sft.jsonl"
EVAL_JSONL = DATA_DIR / "eval_sft.jsonl"

for p in [WORK_DIR, DATA_DIR, OUTPUT_DIR, ADAPTER_DIR, MERGED_DIR]:
    p.mkdir(parents=True, exist_ok=True)


# Training config

MAX_SEQ_LENGTH = 2048

MAX_STEPS = 2500

TRAIN_BATCH_SIZE = 2
EVAL_BATCH_SIZE = 2
GRAD_ACCUM = 8

LEARNING_RATE = 2e-4
SEED = 3407

USE_BF16 = True
USE_FP16 = False

random.seed(SEED)

print("LoRA repo:", LORA_REPO_ID)
print("Merged repo:", MERGED_REPO_ID)
print("Work dir:", WORK_DIR)

Paste Hugging Face token with write access:  ········

Logged in as: oleh13
LoRA repo: oleh13/ord-retro-qwen25-15b-lora
Merged repo: oleh13/ord-retro-qwen25-15b-merged-fp16
Work dir: /content/ord_retro_training

In [5]:
# CELL 3 — Download ORD from Hugging Face and build SFT JSONL
!python -m pip install -q -U ord-schema protobuf

import os
import gc
import json
import gzip
import random
import shutil
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from tqdm.auto import tqdm

from huggingface_hub import HfApi, hf_hub_download

from rdkit import Chem
from rdkit import RDLogger, rdBase

from google.protobuf.json_format import MessageToDict
from ord_schema.proto import dataset_pb2


# RDKit logging
RDLogger.DisableLog("rdApp.warning")
RDLogger.DisableLog("rdApp.error")
rdBase.DisableLog("rdApp.warning")
rdBase.DisableLog("rdApp.error")


# Dataset config

HF_DATASET_ID = "open-reaction-database/ord-data"

MAX_PB_FILES = 120

MAX_TOTAL_EXAMPLES = 30000
MAX_EVAL_EXAMPLES = 800

DEDUP_BY_PRODUCT = True

USE_REACTANTS_IN_PROMPT = False

FORCE_REBUILD_DATASET = True

SEED = 3407
random.seed(SEED)


# Paths

WORK_DIR = Path("/content/ord_retro_training")
ORD_DIR = WORK_DIR / "ord_data"
DATA_DIR = WORK_DIR / "prepared_data"

TRAIN_JSONL = DATA_DIR / "train_sft.jsonl"
EVAL_JSONL = DATA_DIR / "eval_sft.jsonl"
ROWS_JSONL = DATA_DIR / "extracted_rows.jsonl"

ORD_DIR.mkdir(parents=True, exist_ok=True)
DATA_DIR.mkdir(parents=True, exist_ok=True)


# Prompt

SYSTEM_PROMPT_TRAIN = """
You are an expert Organic Chemist specializing in Retrosynthesis.
Your task is to propose practical single-step forward synthesis routes that make the given target molecule.

Rules:
1. Output valid JSON only.
2. Generate exactly 1 route.
3. Each route must contain exactly 1 reaction step.
4. The step product_smiles must equal the target molecule SMILES.
5. Use standard SMILES strings.
6. Use realistic organic chemistry conditions.
7. Do not output Markdown.
8. If evidence reaction IDs are known, include them. Do not invent unsupported evidence.
""".strip()


# Basic chemistry helpers

def canonical_smiles(smiles: Optional[str]) -> Optional[str]:
    if not smiles:
        return None

    smiles = str(smiles).strip()

    if not smiles:
        return None

    try:
        mol = Chem.MolFromSmiles(smiles)

        if mol is None:
            return None

        return Chem.MolToSmiles(mol, canonical=True)

    except Exception:
        return None


def unique_keep_order(values: Iterable[str]) -> List[str]:
    seen = set()
    result = []

    for value in values:
        if value is None:
            continue

        value = str(value).strip()

        if not value or value.lower() in {"none", "null", "nan", "not specified"}:
            continue

        if value not in seen:
            seen.add(value)
            result.append(value)

    return result


def first_identifier_value(obj: Dict[str, Any], identifier_type: str) -> Optional[str]:
    target = identifier_type.upper()

    for ident in obj.get("identifiers", []) or []:
        if str(ident.get("type", "")).upper() == target:
            value = ident.get("value")

            if value:
                return str(value).strip()

    return None


def first_smiles(obj: Dict[str, Any]) -> Optional[str]:
    return canonical_smiles(first_identifier_value(obj, "SMILES"))


def first_name(obj: Dict[str, Any]) -> Optional[str]:
    return first_identifier_value(obj, "NAME")


def format_quantity(q: Optional[Dict[str, Any]]) -> str:
    if not isinstance(q, dict):
        return "not specified"

    value = q.get("value")
    units = q.get("units")

    if value is None:
        return "not specified"

    if units:
        return f"{value} {str(units).lower()}"

    return str(value)


# ORD extraction helpers

def extract_temperature(reaction: Dict[str, Any]) -> str:
    try:
        return format_quantity(reaction["conditions"]["temperature"]["setpoint"])
    except Exception:
        return "not specified"


def extract_pressure(reaction: Dict[str, Any]) -> str:
    try:
        return format_quantity(reaction["conditions"]["pressure"]["setpoint"])
    except Exception:
        return "not specified"


def extract_atmosphere(reaction: Dict[str, Any]) -> str:
    environment = reaction.get("setup", {}).get("environment", {})

    details = environment.get("details")
    env_type = environment.get("type")

    if details:
        return str(details)

    if env_type:
        return str(env_type).lower()

    return "not specified"


def extract_workup(reaction: Dict[str, Any]) -> str:
    parts = []

    for workup in reaction.get("workups", []) or []:
        workup_type = workup.get("type")
        details = workup.get("details")

        if workup_type and details:
            parts.append(f"{workup_type}: {details}")
        elif details:
            parts.append(str(details))
        elif workup_type:
            parts.append(str(workup_type))

    return "; ".join(parts) if parts else "not specified"


def extract_reaction_time(outcome: Dict[str, Any]) -> str:
    return format_quantity(outcome.get("reaction_time"))


def extract_yield_percent(product: Dict[str, Any]) -> Optional[float]:
    yields = []

    for measurement in product.get("measurements", []) or []:
        if str(measurement.get("type", "")).upper() != "YIELD":
            continue

        percentage = measurement.get("percentage") or {}
        value = percentage.get("value")

        if value is None:
            continue

        try:
            yields.append(float(value))
        except Exception:
            pass

    if not yields:
        return None

    return max(yields)


def extract_inputs(reaction: Dict[str, Any]) -> Dict[str, List[str]]:
    reactants = []
    solvents = []
    reagents = []

    inputs = reaction.get("inputs") or {}

    for _, reaction_input in inputs.items():
        for component in reaction_input.get("components", []) or []:
            role = str(component.get("reaction_role", "")).upper().strip()

            smiles = first_smiles(component)
            name = first_name(component)
            label = name or smiles

            if role in {"REACTANT", "STARTING_MATERIAL", "SUBSTRATE"}:
                if smiles:
                    reactants.append(smiles)

            elif role == "SOLVENT":
                if label:
                    solvents.append(label)

            elif role in {"INTERNAL_STANDARD", "PRODUCT"}:
                continue

            else:
                # Reaction role metadata.
                if label:
                    reagents.append(label)

    return {
        "reactants": unique_keep_order(reactants),
        "solvents": unique_keep_order(solvents),
        "reagents": unique_keep_order(reagents),
    }


def extract_best_product(reaction: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    candidates = []

    for outcome in reaction.get("outcomes", []) or []:
        reaction_time = extract_reaction_time(outcome)

        for product in outcome.get("products", []) or []:
            role = str(product.get("reaction_role", "")).upper().strip()

            if role and role != "PRODUCT":
                continue

            product_smiles = first_smiles(product)

            if not product_smiles:
                continue

            y = extract_yield_percent(product)
            desired = bool(product.get("is_desired_product", False))

            score = 0.0

            if desired:
                score += 10000.0

            if y is not None:
                score += 1000.0 + y

            candidates.append(
                {
                    "product_smiles": product_smiles,
                    "yield_percent": y,
                    "reaction_time": reaction_time,
                    "is_desired_product": desired,
                    "score": score,
                }
            )

    if not candidates:
        return None

    candidates.sort(key=lambda x: x["score"], reverse=True)

    return candidates[0]


def extract_reaction_row(reaction: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    reaction_id = str(reaction.get("reaction_id") or reaction.get("id") or "")

    inputs = extract_inputs(reaction)
    product = extract_best_product(reaction)

    if product is None:
        return None

    reactants = inputs["reactants"]
    product_smiles = product["product_smiles"]

    if not reactants or not product_smiles:
        return None

    temperature = extract_temperature(reaction)
    pressure = extract_pressure(reaction)
    atmosphere = extract_atmosphere(reaction)
    workup = extract_workup(reaction)

    condition_details = []

    conditions = reaction.get("conditions") or {}

    if conditions.get("details"):
        condition_details.append(str(conditions["details"]))

    if pressure != "not specified":
        condition_details.append(f"pressure: {pressure}")

    important_conditions = "; ".join(condition_details) if condition_details else "not specified"

    row = {
        "reaction_id": reaction_id,
        "reactants": reactants,
        "product_smiles": product_smiles,
        "reagents": inputs["reagents"],
        "solvents": inputs["solvents"],
        "temperature_celsius": temperature,
        "reaction_time": product["reaction_time"],
        "yield_percent": product["yield_percent"],
        "atmosphere": atmosphere,
        "workup_purification": workup,
        "important_conditions": important_conditions,
    }

    has_useful_label = (
        bool(row["reagents"])
        or bool(row["solvents"])
        or row["temperature_celsius"] != "not specified"
        or row["reaction_time"] != "not specified"
        or row["yield_percent"] is not None
    )

    if not has_useful_label:
        return None

    return row


def iter_ord_reactions_from_pb_gz(pb_gz_path: Path) -> Iterable[Dict[str, Any]]:
    dataset = dataset_pb2.Dataset()

    with gzip.open(pb_gz_path, "rb") as f:
        dataset.ParseFromString(f.read())

    for reaction_proto in dataset.reactions:
        reaction_dict = MessageToDict(
            reaction_proto,
            preserving_proto_field_name=True,
        )

        yield reaction_dict


def quality_score(row: Dict[str, Any]) -> float:
    score = 0.0

    score += 10.0 * len(row["reactants"])
    score += 5.0 * len(row["reagents"])
    score += 5.0 * len(row["solvents"])

    if row["temperature_celsius"] != "not specified":
        score += 5.0

    if row["reaction_time"] != "not specified":
        score += 5.0

    if row["yield_percent"] is not None:
        score += 20.0 + float(row["yield_percent"])

    if row["reaction_id"]:
        score += 2.0

    return score


def deduplicate_rows_by_product(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    best_by_product = {}

    for row in rows:
        product = row["product_smiles"]

        if product not in best_by_product:
            best_by_product[product] = row

        elif quality_score(row) > quality_score(best_by_product[product]):
            best_by_product[product] = row

    return list(best_by_product.values())


# SFT formatting

def build_stoichiometry(row: Dict[str, Any]) -> str:
    if not row["reactants"]:
        return "not specified"

    parts = [
        f"Reactant {i + 1}: 1.0 equiv"
        for i, _ in enumerate(row["reactants"])
    ]

    if row["reagents"]:
        parts.append("reagents/additives: as reported or appropriate")

    return ", ".join(parts)


def make_route_json(row: Dict[str, Any]) -> Dict[str, Any]:
    reagents = "; ".join(row["reagents"]) if row["reagents"] else "not specified"
    solvent = "; ".join(row["solvents"]) if row["solvents"] else "not specified"

    if row["yield_percent"] is None:
        yield_text = "not specified"
    else:
        yield_text = f"{round(float(row['yield_percent']), 1)}%"

    evidence_ids = [row["reaction_id"]] if row["reaction_id"] else []

    return {
        "routes": [
            {
                "route_name": "Single-step ORD-derived route",
                "summary": "One single-step forward synthesis proposal derived from a structured ORD reaction record.",
                "steps": [
                    {
                        "reaction_name": "ORD evidence-based single-step synthesis",
                        "reactants": row["reactants"],
                        "product_smiles": row["product_smiles"],
                        "stoichiometry": build_stoichiometry(row),
                        "reagents": reagents,
                        "solvent": solvent,
                        "temperature_celsius": row["temperature_celsius"],
                        "reaction_time": row["reaction_time"],
                        "atmosphere": row["atmosphere"],
                        "workup_purification": row["workup_purification"],
                        "expected_yield_percent": yield_text,
                        "important_conditions": row["important_conditions"],
                        "rationale": "The proposed single reaction is based on an ORD record where the listed reactants and conditions are associated with formation of the target product.",
                        "objective_fit": "This route is selected as a practical single-step recommendation supported by the available ORD evidence.",
                        "evidence_reaction_ids": evidence_ids,
                    }
                ],
                "objective_fit": "This route is selected because it is a direct single-step ORD-derived proposal for the target product.",
                "evidence_reaction_ids": evidence_ids,
            }
        ],
        "overall_recommendation": "Single-step ORD-derived route is recommended because it directly matches the required one-step format and uses evidence-backed reaction conditions.",
    }


def make_user_prompt(row: Dict[str, Any]) -> str:
    if USE_REACTANTS_IN_PROMPT:
        return f"""Target Molecule SMILES: {row["product_smiles"]}
Known reactants: {json.dumps(row["reactants"], ensure_ascii=False)}
Every route must contain exactly one reaction step.
Every route's only step product_smiles must be this exact target molecule.
Generate exactly 1 distinct route option.
Return valid JSON only."""

    return f"""Target Molecule SMILES: {row["product_smiles"]}
Known reactants are not provided.
Propose one plausible single-step route to make the target molecule.
Every route must contain exactly one reaction step.
Every route's only step product_smiles must be this exact target molecule.
Generate exactly 1 distinct route option.
Return valid JSON only."""


def make_sft_record(row: Dict[str, Any]) -> Dict[str, Any]:
    assistant_json = make_route_json(row)

    return {
        "messages": [
            {
                "role": "system",
                "content": SYSTEM_PROMPT_TRAIN,
            },
            {
                "role": "user",
                "content": make_user_prompt(row),
            },
            {
                "role": "assistant",
                "content": json.dumps(
                    assistant_json,
                    ensure_ascii=False,
                    separators=(",", ":"),
                ),
            },
        ]
    }


def write_jsonl(path: Path, records: Iterable[Dict[str, Any]]) -> int:
    count = 0

    with path.open("w", encoding="utf-8") as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
            count += 1

    return count


# Main: download + parse + write JSONL

if TRAIN_JSONL.exists() and EVAL_JSONL.exists() and not FORCE_REBUILD_DATASET:
    print("Prepared dataset already exists. Skipping rebuild.")
    print("Train:", TRAIN_JSONL)
    print("Eval:", EVAL_JSONL)

else:
    api = HfApi(token=HF_TOKEN)

    print("Listing ORD dataset files...")

    repo_files = api.list_repo_files(
        repo_id=HF_DATASET_ID,
        repo_type="dataset",
    )

    all_pb_paths = sorted(
        [
            f for f in repo_files
            if f.startswith("data/") and f.endswith(".pb.gz")
        ]
    )

    if not all_pb_paths:
        raise RuntimeError("No ORD .pb.gz files found in Hugging Face dataset repo.")

    random.seed(SEED)
    random.shuffle(all_pb_paths)

    selected_pb_paths = (
        all_pb_paths[:MAX_PB_FILES]
        if MAX_PB_FILES is not None
        else all_pb_paths
    )

    print("Total ORD pb.gz files:", len(all_pb_paths))
    print("Selected pb.gz files:", len(selected_pb_paths))

    local_pb_files = []

    for filename in tqdm(selected_pb_paths, desc="Downloading ORD pb.gz files"):
        local_path = hf_hub_download(
            repo_id=HF_DATASET_ID,
            repo_type="dataset",
            filename=filename,
            local_dir=str(ORD_DIR),
            token=HF_TOKEN,
        )

        local_pb_files.append(Path(local_path))

    rows = []
    parse_errors = 0

    for pb_file in tqdm(local_pb_files, desc="Parsing ORD pb.gz files"):
        try:
            for reaction in iter_ord_reactions_from_pb_gz(pb_file):
                row = extract_reaction_row(reaction)

                if row is not None:
                    rows.append(row)

        except Exception as exc:
            parse_errors += 1
            print("Parse failed:", pb_file.name, exc)

    print("Raw extracted rows:", len(rows))
    print("Parse errors:", parse_errors)

    if not rows:
        raise RuntimeError("No usable rows extracted. Increase MAX_PB_FILES.")

    if DEDUP_BY_PRODUCT:
        before = len(rows)
        rows = deduplicate_rows_by_product(rows)
        print(f"Deduplicated by product: {before} -> {len(rows)}")

    random.shuffle(rows)

    if MAX_TOTAL_EXAMPLES is not None:
        rows = rows[:MAX_TOTAL_EXAMPLES]

    with ROWS_JSONL.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    records = [make_sft_record(row) for row in rows]

    eval_size = min(MAX_EVAL_EXAMPLES, max(1, int(0.05 * len(records))))

    eval_records = records[:eval_size]
    train_records = records[eval_size:]

    train_count = write_jsonl(TRAIN_JSONL, train_records)
    eval_count = write_jsonl(EVAL_JSONL, eval_records)

    print("Train records:", train_count)
    print("Eval records:", eval_count)
    print("Rows saved:", ROWS_JSONL)
    print("Train JSONL:", TRAIN_JSONL)
    print("Eval JSONL:", EVAL_JSONL)

    print("\nExample SFT record:")
    print(json.dumps(train_records[0], ensure_ascii=False, indent=2)[:3000])

Listing ORD dataset files...
Total ORD pb.gz files: 550
Selected pb.gz files: 120

Downloading ORD pb.gz files:   0%|          | 0/120 [00:00<?, ?it/s]

data/23/ord_dataset-2369b9b9f44641b19305(…):   0%|          | 0.00/923k [00:00<?, ?B/s]

data/46/ord_dataset-46d216f2c4374ef5b9df(…):   0%|          | 0.00/4.63M [00:00<?, ?B/s]

data/4a/ord_dataset-4ad5db8537994579bef5(…):   0%|          | 0.00/2.86M [00:00<?, ?B/s]

data/ac/ord_dataset-acbdbaa766314b66a982(…):   0%|          | 0.00/906k [00:00<?, ?B/s]

data/9f/ord_dataset-9f54014563f44962b72e(…):   0%|          | 0.00/782k [00:00<?, ?B/s]

data/6f/ord_dataset-6f715747ea754945a2f0(…):   0%|          | 0.00/791k [00:00<?, ?B/s]

data/ab/ord_dataset-abe42048f0b84fa88446(…):   0%|          | 0.00/1.04M [00:00<?, ?B/s]

data/d0/ord_dataset-d0003732f14e4648a00d(…):   0%|          | 0.00/2.05M [00:00<?, ?B/s]

data/1c/ord_dataset-1c0bae7388cf460091d5(…):   0%|          | 0.00/1.95M [00:00<?, ?B/s]

data/6a/ord_dataset-6a0bfcdf53a64c079878(…):   0%|          | 0.00/6.42k [00:00<?, ?B/s]

data/21/ord_dataset-21c1b1c06c7e4e09a38b(…):   0%|          | 0.00/2.68M [00:00<?, ?B/s]

data/2b/ord_dataset-2be30f5d8dcd471aa6ad(…):   0%|          | 0.00/8.16k [00:00<?, ?B/s]

data/c8/ord_dataset-c8db783fb93842e89cdc(…):   0%|          | 0.00/922k [00:00<?, ?B/s]

data/56/ord_dataset-56c07ce5503b46d1805b(…):   0%|          | 0.00/640k [00:00<?, ?B/s]

data/28/ord_dataset-28b19b59e93c47698a5a(…):   0%|          | 0.00/448k [00:00<?, ?B/s]

data/3d/ord_dataset-3d470a6df4a04b1996e0(…):   0%|          | 0.00/673k [00:00<?, ?B/s]

data/76/ord_dataset-769fac6048e548eca2d4(…):   0%|          | 0.00/938k [00:00<?, ?B/s]

data/12/ord_dataset-12a0ec4f3cda46e2badc(…):   0%|          | 0.00/266k [00:00<?, ?B/s]

data/10/ord_dataset-10360c60962940178e4b(…):   0%|          | 0.00/430k [00:00<?, ?B/s]

data/f4/ord_dataset-f4512fe8cd804ac79da6(…):   0%|          | 0.00/3.04M [00:00<?, ?B/s]

data/47/ord_dataset-4731a430f0af464b83e8(…):   0%|          | 0.00/729k [00:00<?, ?B/s]

data/82/ord_dataset-8214eb8444a44dc2900c(…):   0%|          | 0.00/3.80M [00:00<?, ?B/s]

data/bd/ord_dataset-bd998d3fe946475e8354(…):   0%|          | 0.00/1.37M [00:00<?, ?B/s]

data/27/ord_dataset-275a3da8f45f4536ad29(…):   0%|          | 0.00/6.29M [00:00<?, ?B/s]

data/15/ord_dataset-15cdba4c7f064b3f9cd7(…):   0%|          | 0.00/2.28M [00:00<?, ?B/s]

data/18/ord_dataset-1884c7bf3d544afdb8d1(…):   0%|          | 0.00/2.28M [00:00<?, ?B/s]

data/2e/ord_dataset-2e96d163c3f64eb5b470(…):   0%|          | 0.00/859k [00:00<?, ?B/s]

data/d2/ord_dataset-d24cc23b3db94284bb83(…):   0%|          | 0.00/7.39M [00:00<?, ?B/s]

data/89/ord_dataset-89b083710e2d441aa004(…):   0%|          | 0.00/9.26k [00:00<?, ?B/s]

data/46/ord_dataset-46ff9a32d9e04016b938(…):   0%|          | 0.00/315k [00:00<?, ?B/s]

data/26/ord_dataset-266f60b4555945d6afb2(…):   0%|          | 0.00/5.25M [00:00<?, ?B/s]

data/b2/ord_dataset-b2a00a09c8494aaf9348(…):   0%|          | 0.00/404k [00:00<?, ?B/s]

data/f0/ord_dataset-f027aa93238e424fbbf9(…):   0%|          | 0.00/1.92M [00:00<?, ?B/s]

data/5c/ord_dataset-5c25f386f4664070a72d(…):   0%|          | 0.00/591k [00:00<?, ?B/s]

data/0b/ord_dataset-0b24d1f58a024ed7bc2b(…):   0%|          | 0.00/2.27M [00:00<?, ?B/s]

data/ed/ord_dataset-ed846b4b229e4bb09ad9(…):   0%|          | 0.00/2.49M [00:00<?, ?B/s]

data/0b/ord_dataset-0b32b90cc77b4a3db47a(…):   0%|          | 0.00/4.96M [00:00<?, ?B/s]

data/87/ord_dataset-87aeeef7c91d4312a992(…):   0%|          | 0.00/546k [00:00<?, ?B/s]

data/3e/ord_dataset-3e8f24b5bc8e4d8bb9b6(…):   0%|          | 0.00/1.64M [00:00<?, ?B/s]

data/d2/ord_dataset-d26118acda314269becc(…):   0%|          | 0.00/102k [00:00<?, ?B/s]

data/78/ord_dataset-78c3f723155a4347a902(…):   0%|          | 0.00/5.41M [00:00<?, ?B/s]

data/5d/ord_dataset-5df93261afc143c3ae91(…):   0%|          | 0.00/4.37M [00:00<?, ?B/s]

data/03/ord_dataset-0316886541d943548985(…):   0%|          | 0.00/12.0k [00:00<?, ?B/s]

data/52/ord_dataset-5237a168f9214b7ca3db(…):   0%|          | 0.00/555k [00:00<?, ?B/s]

data/a9/ord_dataset-a9ba4801408c4b019228(…):   0%|          | 0.00/1.56M [00:00<?, ?B/s]

data/1a/ord_dataset-1acb071a357f438ea599(…):   0%|          | 0.00/1.13M [00:00<?, ?B/s]

data/54/ord_dataset-5481550056a14935b76e(…):   0%|          | 0.00/6.85M [00:00<?, ?B/s]

data/37/ord_dataset-37b0416f244344a08cf3(…):   0%|          | 0.00/2.13M [00:00<?, ?B/s]

data/85/ord_dataset-85c00026681b46f89ef8(…):   0%|          | 0.00/2.86M [00:00<?, ?B/s]

data/97/ord_dataset-97eb2ab57fec4160922c(…):   0%|          | 0.00/7.00M [00:00<?, ?B/s]

data/d3/ord_dataset-d31180f42ced44719fd9(…):   0%|          | 0.00/2.05M [00:00<?, ?B/s]

data/7f/ord_dataset-7fed188163cf4ccca934(…):   0%|          | 0.00/2.32M [00:00<?, ?B/s]

data/23/ord_dataset-2345345e84034af393f9(…):   0%|          | 0.00/795k [00:00<?, ?B/s]

data/76/ord_dataset-76dd1b78ee414d2da0ed(…):   0%|          | 0.00/3.92M [00:00<?, ?B/s]

data/f8/ord_dataset-f886e51ba1484c76a94b(…):   0%|          | 0.00/3.61M [00:00<?, ?B/s]

data/cf/ord_dataset-cf82113c6dd341d4a014(…):   0%|          | 0.00/1.01M [00:00<?, ?B/s]

data/45/ord_dataset-45d20d09e4d64f45bdd4(…):   0%|          | 0.00/869k [00:00<?, ?B/s]

data/bf/ord_dataset-bf316bf78f4f45d4b275(…):   0%|          | 0.00/2.20M [00:00<?, ?B/s]

data/48/ord_dataset-48929f64ce614f1181a5(…):   0%|          | 0.00/737k [00:00<?, ?B/s]

data/dd/ord_dataset-ddb1b60bec5c45e9a293(…):   0%|          | 0.00/950k [00:00<?, ?B/s]

data/e2/ord_dataset-e2b35e721c2741999b00(…):   0%|          | 0.00/2.83M [00:00<?, ?B/s]

data/a2/ord_dataset-a2ae447c4340438c8c3a(…):   0%|          | 0.00/1.13M [00:00<?, ?B/s]

data/38/ord_dataset-380e279f82154dba9e08(…):   0%|          | 0.00/5.76M [00:00<?, ?B/s]

data/f4/ord_dataset-f483e698250b4da0a84f(…):   0%|          | 0.00/2.32M [00:00<?, ?B/s]

data/41/ord_dataset-41558b7e18dd41999311(…):   0%|          | 0.00/768k [00:00<?, ?B/s]

data/03/ord_dataset-0387783899c642a8b7eb(…):   0%|          | 0.00/3.18M [00:00<?, ?B/s]

data/ed/ord_dataset-ed680843f6d14f5c9901(…):   0%|          | 0.00/3.58M [00:00<?, ?B/s]

data/64/ord_dataset-64e3763e75b242749501(…):   0%|          | 0.00/233k [00:00<?, ?B/s]

data/fa/ord_dataset-fa3b512e2d924b9b9653(…):   0%|          | 0.00/1.08M [00:00<?, ?B/s]

data/f3/ord_dataset-f3b9c7d90d3648ff8136(…):   0%|          | 0.00/790k [00:00<?, ?B/s]

data/5e/ord_dataset-5ebf3d05077a4f7fb91a(…):   0%|          | 0.00/930k [00:00<?, ?B/s]

data/b9/ord_dataset-b90b48a6c23149a1aa2d(…):   0%|          | 0.00/790k [00:00<?, ?B/s]

data/68/ord_dataset-68715347640045adb1b0(…):   0%|          | 0.00/5.22M [00:00<?, ?B/s]

data/e6/ord_dataset-e61c1950b2fc468dbf07(…):   0%|          | 0.00/509k [00:00<?, ?B/s]

data/15/ord_dataset-159c363342e44b539e7a(…):   0%|          | 0.00/906k [00:00<?, ?B/s]

data/c5/ord_dataset-c5b00523487a4211a194(…):   0%|          | 0.00/204k [00:00<?, ?B/s]

data/0b/ord_dataset-0bf72e95d80743729fdb(…):   0%|          | 0.00/873k [00:00<?, ?B/s]

data/ea/ord_dataset-eacfee6d16d8455a9334(…):   0%|          | 0.00/6.08M [00:00<?, ?B/s]

data/70/ord_dataset-70899a0178cc44148274(…):   0%|          | 0.00/4.13M [00:00<?, ?B/s]

data/05/ord_dataset-053897d9b1744303b2fd(…):   0%|          | 0.00/653k [00:00<?, ?B/s]

data/4a/ord_dataset-4a5b4fffffb34daa876f(…):   0%|          | 0.00/1.23M [00:00<?, ?B/s]

data/bf/ord_dataset-bfcf5a01f1a04ec585ba(…):   0%|          | 0.00/1.21M [00:00<?, ?B/s]

data/38/ord_dataset-386da077ab2340638cad(…):   0%|          | 0.00/1.78M [00:00<?, ?B/s]

data/19/ord_dataset-19b9e29d593f4660ab77(…):   0%|          | 0.00/727k [00:00<?, ?B/s]

data/cb/ord_dataset-cbcc4048add7468e850b(…):   0%|          | 0.00/18.9k [00:00<?, ?B/s]

data/bb/ord_dataset-bbd7e53f000345838ad4(…):   0%|          | 0.00/1.51M [00:00<?, ?B/s]

data/84/ord_dataset-843ef38b45484f72826f(…):   0%|          | 0.00/1.93M [00:00<?, ?B/s]

data/74/ord_dataset-7448b89163bf426c9d97(…):   0%|          | 0.00/5.31M [00:00<?, ?B/s]

data/f5/ord_dataset-f5dc3e448c204058b116(…):   0%|          | 0.00/808k [00:00<?, ?B/s]

data/84/ord_dataset-846d411edee44814931e(…):   0%|          | 0.00/2.31M [00:00<?, ?B/s]

data/1b/ord_dataset-1b0cd79134f0450eaac8(…):   0%|          | 0.00/3.00M [00:00<?, ?B/s]

data/e9/ord_dataset-e90cd41afe844e498754(…):   0%|          | 0.00/2.75M [00:00<?, ?B/s]

data/6d/ord_dataset-6d65cff9c5f346249fd7(…):   0%|          | 0.00/9.35M [00:00<?, ?B/s]

data/b6/ord_dataset-b67d30cd146f49dcbf24(…):   0%|          | 0.00/892k [00:00<?, ?B/s]

data/2d/ord_dataset-2d21ceeb77844edc9eae(…):   0%|          | 0.00/476k [00:00<?, ?B/s]

data/d5/ord_dataset-d5bb2294ac964841b8ff(…):   0%|          | 0.00/1.46M [00:00<?, ?B/s]

data/cf/ord_dataset-cfad8b3f00044bcda60a(…):   0%|          | 0.00/7.11M [00:00<?, ?B/s]

data/a2/ord_dataset-a2d74266062e4398bc26(…):   0%|          | 0.00/1.86M [00:00<?, ?B/s]

data/4e/ord_dataset-4e81c470cc3b429faf5e(…):   0%|          | 0.00/4.33M [00:00<?, ?B/s]

data/b1/ord_dataset-b18df02d6e9345faa0f2(…):   0%|          | 0.00/1.52M [00:00<?, ?B/s]

data/2e/ord_dataset-2e58cb8db2bf482bbea2(…):   0%|          | 0.00/2.63M [00:00<?, ?B/s]

data/a5/ord_dataset-a5669edbeffe43bf8514(…):   0%|          | 0.00/1.04M [00:00<?, ?B/s]

data/63/ord_dataset-632f0d9054ce41aba87d(…):   0%|          | 0.00/1.66M [00:00<?, ?B/s]

data/2a/ord_dataset-2ada3fda46fc44719ba0(…):   0%|          | 0.00/759k [00:00<?, ?B/s]

data/f6/ord_dataset-f6fafbb8ce5f4ef099be(…):   0%|          | 0.00/1.18M [00:00<?, ?B/s]

data/29/ord_dataset-2952e63264f5422a84e1(…):   0%|          | 0.00/2.09M [00:00<?, ?B/s]

data/90/ord_dataset-90b0aa1f83334a02919b(…):   0%|          | 0.00/3.19M [00:00<?, ?B/s]

data/72/ord_dataset-72d9f7ef86df410fac47(…):   0%|          | 0.00/484k [00:00<?, ?B/s]

data/6c/ord_dataset-6c36eb0f817d4144988b(…):   0%|          | 0.00/1.58M [00:00<?, ?B/s]

data/59/ord_dataset-59f453c3a3d34a89bfd9(…):   0%|          | 0.00/985k [00:00<?, ?B/s]

data/47/ord_dataset-47eaacc46c3a4487bbdf(…):   0%|          | 0.00/8.75M [00:00<?, ?B/s]

data/5e/ord_dataset-5e6956e6e8c24a168866(…):   0%|          | 0.00/6.04M [00:00<?, ?B/s]

data/8c/ord_dataset-8cbb58558c904b2b85fa(…):   0%|          | 0.00/854k [00:00<?, ?B/s]

data/3f/ord_dataset-3f9174c7efcb4f31becb(…):   0%|          | 0.00/1.56M [00:00<?, ?B/s]

data/b1/ord_dataset-b1a34bc8c1204d51a772(…):   0%|          | 0.00/1.39M [00:00<?, ?B/s]

data/ce/ord_dataset-ce71a906ea9c4399a201(…):   0%|          | 0.00/1.31M [00:00<?, ?B/s]

data/5e/ord_dataset-5eb2900a93c842ee98f2(…):   0%|          | 0.00/1.16M [00:00<?, ?B/s]

data/56/ord_dataset-56a22bc0c3b14f87b9aa(…):   0%|          | 0.00/1.84M [00:00<?, ?B/s]

data/9b/ord_dataset-9b8aa9a7835143ef8ce3(…):   0%|          | 0.00/91.7k [00:00<?, ?B/s]

data/31/ord_dataset-31641fb65b34430fa743(…):   0%|          | 0.00/5.34M [00:00<?, ?B/s]

Parsing ORD pb.gz files:   0%|          | 0/120 [00:00<?, ?it/s]

Raw extracted rows: 396580
Parse errors: 0
Deduplicated by product: 396580 -> 265353
Train records: 29200
Eval records: 800
Rows saved: /content/ord_retro_training/prepared_data/extracted_rows.jsonl
Train JSONL: /content/ord_retro_training/prepared_data/train_sft.jsonl
Eval JSONL: /content/ord_retro_training/prepared_data/eval_sft.jsonl

Example SFT record:
{
  "messages": [
    {
      "role": "system",
      "content": "You are an expert Organic Chemist specializing in Retrosynthesis.\nYour task is to propose practical single-step forward synthesis routes that make the given target molecule.\n\nRules:\n1. Output valid JSON only.\n2. Generate exactly 1 route.\n3. Each route must contain exactly 1 reaction step.\n4. The step product_smiles must equal the target molecule SMILES.\n5. Use standard SMILES strings.\n6. Use realistic organic chemistry conditions.\n7. Do not output Markdown.\n8. If evidence reaction IDs are known, include them. Do not invent unsupported evidence."
    },
    {
      "role": "user",
      "content": "Target Molecule SMILES: CC(C)CN(C(=O)c1nc2ccccc2n1CCc1ncon1)[C@@H]1CNC[C@H](C(=O)N2CCOCC2)C1.Cl.Cl\nKnown reactants are not provided.\nPropose one plausible single-step route to make the target molecule.\nEvery route must contain exactly one reaction step.\nEvery route's only step product_smiles must be this exact target molecule.\nGenerate exactly 1 distinct route option.\nReturn valid JSON only."
    },
    {
      "role": "assistant",
      "content": "{\"routes\":[{\"route_name\":\"Single-step ORD-derived route\",\"summary\":\"One single-step forward synthesis proposal derived from a structured ORD reaction record.\",\"steps\":[{\"reaction_name\":\"ORD evidence-based single-step synthesis\",\"reactants\":[\"CC(C)CN(C(=O)c1nc2ccccc2n1CCc1ncon1)[C@H]1C[C@@H](C(=O)N2CCOCC2)CN(C(=O)OC(C)(C)C)C1\",\"CCOC(C)=O.Cl\"],\"product_smiles\":\"CC(C)CN(C(=O)c1nc2ccccc2n1CCc1ncon1)[C@@H]1CNC[C@H](C(=O)N2CCOCC2)C1.Cl.Cl\",\"stoichiometry\":\"Reactant 1: 1.0 equiv, Reactant 2: 1.0 equiv\",\"reagents\":\"not specified\",\"solvent\":\"not specified\",\"temperature_celsius\":\"not specified\",\"reaction_time\":\"2.0 hour\",\"atmosphere\":\"not specified\",\"workup_purification\":\"CONCENTRATION: The reaction mixture was concentrated; CONCENTRATION: the eluted fraction was concentrated under reduced pressure; ADDITION: The residue was diluted with aqueous sodium bicarbonate; EXTRACTION: the mixture was extracted with ethyl acetate; WASH: The extract was washed with saturated brine; DRY_WITH_MATERIAL: dried over anhydrous sodium sulfate; ADDITION: 4M Hydrogen chloride-ethyl acetate (1 ml) was added; STIRRING: the mixture was stirred for min; CUSTOM: The solvent was evaporated under reduced pressure\",\"expected_yield_percent\":\"not specified\",\"important_conditions\":\"See reaction.notes.procedure_details.\",\"rationale\":\"The proposed single reaction is based on an ORD record where the listed reactants and conditions are associated with formation of the target product.\",\"objective_fit\":\"This route is selected as a practical single-step recommendation supported by the available ORD evidence.\",\"evidence_reaction_ids\":[\"ord-ac380407ec03462b9a84a2005cd223b6\"]}],\"objective_fit\":\"This route is selected because it is a direct single-step ORD-derived proposal for the target product.\",\"

In [6]:
# CELL 4 — Load tokenizer and render chat dataset

from datasets import load_dataset
from transformers import AutoTokenizer

assert TRAIN_JSONL.exists(), f"Missing {TRAIN_JSONL}"
assert EVAL_JSONL.exists(), f"Missing {EVAL_JSONL}"

tokenizer = AutoTokenizer.from_pretrained(
    BASE_MODEL,
    trust_remote_code=True,
    use_fast=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "right"

raw_dataset = load_dataset(
    "json",
    data_files={
        "train": str(TRAIN_JSONL),
        "eval": str(EVAL_JSONL),
    },
)

def render_text(example):
    text = tokenizer.apply_chat_template(
        example["messages"],
        tokenize=False,
        add_generation_prompt=False,
    )

    if tokenizer.eos_token and not text.endswith(tokenizer.eos_token):
        text += tokenizer.eos_token

    return {"text": text}


rendered_train = raw_dataset["train"].map(
    render_text,
    remove_columns=raw_dataset["train"].column_names,
)

rendered_eval = raw_dataset["eval"].map(
    render_text,
    remove_columns=raw_dataset["eval"].column_names,
)


def tokenize_batch(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
        padding=False,
    )


train_dataset = rendered_train.map(
    tokenize_batch,
    batched=True,
    remove_columns=["text"],
    num_proc=4,
)

eval_dataset = rendered_eval.map(
    tokenize_batch,
    batched=True,
    remove_columns=["text"],
    num_proc=4,
)

print("Train rows:", len(train_dataset))
print("Eval rows:", len(eval_dataset))
print("Example token length:", len(train_dataset[0]["input_ids"]))

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating eval split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/29200 [00:00<?, ? examples/s]

Map:   0%|          | 0/800 [00:00<?, ? examples/s]

Map (num_proc=4):   0%|          | 0/29200 [00:00<?, ? examples/s]

Map (num_proc=4):   0%|          | 0/800 [00:00<?, ? examples/s]

Train rows: 29200
Eval rows: 800
Example token length: 790

In [7]:
# CELL 5 — Load Qwen in 4-bit and apply LoRA

from transformers import AutoModelForCausalLM, BitsAndBytesConfig
from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
)

gc.collect()
torch.cuda.empty_cache()

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)

model.config.use_cache = False
model.config.torch_dtype = torch.bfloat16

model = prepare_model_for_kbit_training(
    model,
    use_gradient_checkpointing=True,
)

peft_config = LoraConfig(
    r=32,
    lora_alpha=64,
    lora_dropout=0.0,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
)

model = get_peft_model(model, peft_config)

model.print_trainable_parameters()

dtype_counts = {}

for name, param in model.named_parameters():
    if param.requires_grad:
        dtype_counts[str(param.dtype)] = dtype_counts.get(str(param.dtype), 0) + param.numel()

print("Trainable dtype counts:", dtype_counts)

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

trainable params: 36,929,536 || all params: 1,580,643,840 || trainable%: 2.3364
Trainable dtype counts: {'torch.float32': 36929536}

In [8]:
# CELL 6 — Train

from transformers import Trainer, TrainingArguments


def causal_lm_data_collator(features):
    batch = tokenizer.pad(
        features,
        padding=True,
        return_tensors="pt",
    )

    labels = batch["input_ids"].clone()
    labels[batch["attention_mask"] == 0] = -100
    batch["labels"] = labels

    return batch


WARMUP_STEPS = max(1, int(MAX_STEPS * 0.05))

common_args = dict(
    output_dir=str(OUTPUT_DIR),

    per_device_train_batch_size=TRAIN_BATCH_SIZE,
    per_device_eval_batch_size=EVAL_BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUM,

    max_steps=MAX_STEPS,
    warmup_steps=WARMUP_STEPS,
    learning_rate=LEARNING_RATE,
    lr_scheduler_type="cosine",
    optim="paged_adamw_8bit",
    weight_decay=0.01,

    bf16=USE_BF16,
    fp16=USE_FP16,

    logging_steps=10,

    eval_steps=250,
    save_steps=250,
    save_total_limit=3,

    report_to="none",
    seed=SEED,

    remove_unused_columns=False,
    gradient_checkpointing=True,

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

try:
    training_args = TrainingArguments(
        **common_args,
        eval_strategy="steps",
        save_strategy="steps",
    )
except TypeError:
    training_args = TrainingArguments(
        **common_args,
        evaluation_strategy="steps",
        save_strategy="steps",
    )


trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=causal_lm_data_collator,
    processing_class=tokenizer,
)

checkpoint_dirs = sorted(OUTPUT_DIR.glob("checkpoint-*"))

if checkpoint_dirs:
    print("Found checkpoints:")
    for ckpt in checkpoint_dirs:
        print(" -", ckpt)

    latest_checkpoint = str(checkpoint_dirs[-1])
    print("Resuming from:", latest_checkpoint)

    train_result = trainer.train(resume_from_checkpoint=latest_checkpoint)
else:
    train_result = trainer.train()

print(train_result)

eval_result = trainer.evaluate()
print(eval_result)

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=2500, training_loss=0.3605717908859253, metrics={'train_runtime': 8985.0778, 'train_samples_per_second': 4.452, 'train_steps_per_second': 0.278, 'total_flos': 2.3967754788652646e+17, 'train_loss': 0.3605717908859253, 'epoch': 1.36986301369863})

{'eval_loss': 0.3186369836330414}

In [9]:
# CELL 7 — Save and upload LoRA adapter

from huggingface_hub import HfApi

ADAPTER_DIR.mkdir(parents=True, exist_ok=True)

model.save_pretrained(str(ADAPTER_DIR))
tokenizer.save_pretrained(str(ADAPTER_DIR))

adapter_readme = f"""---
license: apache-2.0
base_model: {BASE_MODEL}
tags:
- chemistry
- retrosynthesis
- organic-chemistry
- qlora
- lora
- ord
---

# {HF_MODEL_REPO_NAME} LoRA adapter

QLoRA adapter fine-tuned on ORD-derived single-step reaction records.

Task:

target molecule SMILES -> one single-step JSON synthesis proposal.

Training setup:

- Base model: {BASE_MODEL}
- Max sequence length: {MAX_SEQ_LENGTH}
- Max steps: {MAX_STEPS}
- LoRA rank: 32
- BF16: {USE_BF16}

Limitations:

- Academic/diploma demonstration only.
- Not authoritative chemistry guidance.
- Product-only retrosynthesis is under-constrained.
- Generated routes must be manually checked.
"""

(ADAPTER_DIR / "README.md").write_text(adapter_readme, encoding="utf-8")

api = HfApi(token=HF_TOKEN)

api.create_repo(
    repo_id=LORA_REPO_ID,
    repo_type="model",
    exist_ok=True,
)

api.upload_folder(
    folder_path=str(ADAPTER_DIR),
    repo_id=LORA_REPO_ID,
    repo_type="model",
)

print("Uploaded LoRA adapter:", LORA_REPO_ID)

Uploaded LoRA adapter: oleh13/ord-retro-qwen25-15b-lora

In [11]:
# CELL 8 — Test generation

from rdkit import Chem


SYSTEM_PROMPT_TRAIN = """
You are an expert Organic Chemist specializing in Retrosynthesis.
Your task is to propose practical single-step forward synthesis routes that make the given target molecule.

Rules:
1. Output valid JSON only.
2. Generate exactly 1 route.
3. Each route must contain exactly 1 reaction step.
4. The step product_smiles must equal the target molecule SMILES.
5. Use standard SMILES strings.
6. Use realistic organic chemistry conditions.
7. Do not output Markdown.
8. If evidence reaction IDs are known, include them. Do not invent unsupported evidence.
""".strip()


def canonical_smiles(smiles: Optional[str]) -> Optional[str]:
    if not smiles:
        return None

    mol = Chem.MolFromSmiles(str(smiles).strip())

    if mol is None:
        return None

    return Chem.MolToSmiles(mol, canonical=True)


def extract_json_object(text: str) -> str:
    text = text.strip()
    first = text.find("{")
    last = text.rfind("}")

    if first == -1 or last == -1 or last <= first:
        raise ValueError("No JSON object found in model output")

    return text[first:last + 1]


def generate_route(target_smiles: str, max_new_tokens: int = 1400) -> Dict[str, Any]:
    target = canonical_smiles(target_smiles)

    if target is None:
        raise ValueError(f"Invalid target SMILES: {target_smiles}")

    user_prompt = f"""Target Molecule SMILES: {target}
Known reactants are not provided.
Propose one plausible single-step route to make the target molecule.
Every route must contain exactly one reaction step.
Every route's only step product_smiles must be this exact target molecule.
Generate exactly 1 distinct route option.
Return valid JSON only."""

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT_TRAIN},
        {"role": "user", "content": user_prompt},
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tokenizer([prompt], return_tensors="pt").to(model.device)

    model.eval()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.1,
            top_p=0.9,
            do_sample=True,
            repetition_penalty=1.05,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    generated = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True,
    )

    clean = extract_json_object(generated)

    return json.loads(clean)


test_target = "N#CCc1ccccc1"

result = generate_route(test_target)

print(json.dumps(result, ensure_ascii=False, indent=2))

{
  "routes": [
    {
      "route_name": "Single-step ORD-derived route",
      "summary": "One single-step forward synthesis proposal derived from a structured ORD reaction record.",
      "steps": [
        {
          "reaction_name": "ORD evidence-based single-step synthesis",
          "reactants": [
            "N#CCc1ccccc1.Cl",
            "[H][H]"
          ],
          "product_smiles": "N#CCc1ccccc1",
          "stoichiometry": "Reactant 1: 1.0 equiv, Reactant 2: 1.0 equiv, reagents/additives: as reported or appropriate",
          "reagents": "palladium on carbon",
          "solvent": "ethanol",
          "temperature_celsius": "not specified",
          "reaction_time": "not specified",
          "atmosphere": "not specified",
          "workup_purification": "FILTRATION: The catalyst was filtered off; CONCENTRATION: the filtrate was concentrated under reduced pressure; CUSTOM: The residue was purified by silica gel column chromatography (hexane/ethyl acetate=100/0→90/10)",
          "expected_yield_percent": "94.0%",
          "important_conditions": "See reaction.notes.procedure_details.",
          "rationale": "The proposed single reaction is based on an ORD record where the listed reactants and conditions are associated with formation of the target product.",
          "objective_fit": "This route is selected as a practical single-step recommendation supported by the available ORD evidence.",
          "evidence_reaction_ids": [
            "ord-7b9d6f9a89704698972829226707023d"
          ]
        }
      ],
      "objective_fit": "This route is selected because it is a direct single-step ORD-derived proposal for the target product.",
      "evidence_reaction_ids": [
        "ord-7b9d6f9a89704698972829226707023d"
      ]
    }
  ],
  "overall_recommendation": "Single-step ORD-derived route is recommended because it directly matches the required one-step format and uses evidence-backed reaction conditions."
}

In [12]:
# CELL 9 — Merge LoRA into FP16 HF model

!python -m pip uninstall -y -q torchao

import gc
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

try:
    del trainer
except Exception:
    pass

try:
    del model
except Exception:
    pass

gc.collect()
torch.cuda.empty_cache()

MERGED_DIR.mkdir(parents=True, exist_ok=True)

tokenizer = AutoTokenizer.from_pretrained(
    BASE_MODEL,
    trust_remote_code=True,
    use_fast=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token


base_model_fp16 = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float16,
    device_map="cpu",
    trust_remote_code=True,
    low_cpu_mem_usage=True,
)

merged_model = PeftModel.from_pretrained(
    base_model_fp16,
    str(ADAPTER_DIR),
    torch_dtype=torch.float16,
)

merged_model = merged_model.merge_and_unload()

merged_model.save_pretrained(
    str(MERGED_DIR),
    safe_serialization=True,
    max_shard_size="2GB",
)

tokenizer.save_pretrained(str(MERGED_DIR))

print("Merged model saved to:", MERGED_DIR)

for p in MERGED_DIR.iterdir():
    print(" -", p.name)

WARNING: Skipping torchao as it is not installed.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/2 [00:00<?, ?it/s]

Merged model saved to: /content/ord_retro_training/merged_fp16
 - model-00002-of-00002.safetensors
 - tokenizer_config.json
 - model.safetensors.index.json
 - tokenizer.json
 - config.json
 - generation_config.json
 - chat_template.jinja
 - model-00001-of-00002.safetensors

In [13]:
# CELL 10 — Upload merged FP16 model to HF

from huggingface_hub import HfApi

assert MERGED_DIR.exists(), f"Missing merged model folder: {MERGED_DIR}"

api = HfApi(token=HF_TOKEN)

api.create_repo(
    repo_id=MERGED_REPO_ID,
    repo_type="model",
    exist_ok=True,
)

api.upload_folder(
    folder_path=str(MERGED_DIR),
    repo_id=MERGED_REPO_ID,
    repo_type="model",
)

print("Uploaded merged FP16 model:", MERGED_REPO_ID)

Uploaded merged FP16 model: oleh13/ord-retro-qwen25-15b-merged-fp16